name: URLBlueprints
attributes:
  ORGANIZATIONNAME: LionSoftware.org
options:
  createIntermediateGroups: true
  xcodeVersion: 11.3
  groupSortPosition: top
  deploymentTarget:
    iOS: "8.0"
    macOS: "10.10"
    watchOS: "2.0"
    tvOS: "9.0"
configs:
  Debug: debug
  Release: release
fileGroups:
  - Configurations
  - Package.swift
configFiles:
  Debug: Configurations/Debug.xcconfig
  Release: Configurations/Release.xcconfig
schemes:
  URLBlueprints_iOS:
    build:
      targets:
        URLBlueprints_iOS: all
    run:
      config: Debug
    test:
      config: Debug
      targets: [URLBlueprintsTests_iOS]
      gatherCoverageData: true
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
  URLBlueprints_macOS:
    build:
      targets:
        URLBlueprints_macOS: all
    run:
      config: Debug
    test:
      config: Debug
      targets: [URLBlueprintsTests_macOS]
      gatherCoverageData: true
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
  URLBlueprints_watchOS:
    build:
      targets:
        URLBlueprints_watchOS: all
    run:
      config: Debug
    test:
      config: Debug
      targets: []
      gatherCoverageData: true
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
  URLBlueprints_tvOS:
    build:
      targets:
        URLBlueprints_tvOS: all
    run:
      config: Debug
    test:
      config: Debug
      targets: [URLBlueprintsTests_tvOS]
      gatherCoverageData: true
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

targets:
  URLBlueprints:
    type: framework
    platform: [macOS, iOS, tvOS, watchOS]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: $(URL_BLUEPRINTS_BUNDLE_IDENTIFIER)
        PROVISIONING_PROFILE_SPECIFIER: $(URL_BLUEPRINTS_PROVISIONING_PROFILE_SPECIFIER)
    sources:
      - path: URLBlueprints
  URLBlueprintsTests:
    type: bundle.unit-test
    platform: [macOS, iOS, tvOS]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: org.lionsoftware.url-blueprints.tests
        # empty specifier resolves to "Automatic"
        PROVISIONING_PROFILE_SPECIFIER: 
    sources:
      - path: URLBlueprintsTests
    dependencies:
      - target: URLBlueprints_macOS
  Example:
    type: tool
    platform: macOS
    deploymentTarget: 10.15
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: org.lionsoftware.url-blueprints.example
        # empty specifier resolves to "Automatic"
        PROVISIONING_PROFILE_SPECIFIER:
        CURRENT_PROJECT_VERSION: 1
    sources:
      - path: Example
    dependencies:
      - target: URLBlueprints_macOS
    postBuildScripts:
      - script: |
                "${PODS_ROOT}/SwiftLint/swiftlint"
        name: SwiftLint
